### ISSUE TITLE
StackOverflowError in GLM.GlmResp

### ISSUE THREAD

**Issue by goerch** [JuliaAI/MLJGLMInterface.jl#8]
The test case

```
using MLJ

X, y = @load_boston

model = (@load LinearRegressor pkg="GLM")()
_machine = machine(model, X, y)
fit!(_machine)
y_hat = predict(_machine, X)
_rmse = rmse(y, y_hat)
println("rmse = ", _rmse)
```

crashes with 

```
[ Info: For silent loading, specify `verbosity=0`.
import MLJGLMInterface ✔
[ Info: Training Machine{LinearRegressor,…} @076.
┌ Error: Problem fitting the machine Machine{LinearRegressor,…} @076.
└ @ MLJBase C:\Users\Win10\.julia\packages\MLJBase\j0qGA\src\machines.jl:484
[ Info: Running type checks...
[ Info: Type checks okay.
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] GLM.GlmResp(y::SubArray{Float64, 1, Matrix{Float64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}, d::Distributions.Normal{Float64}, l::GLM.IdentityLink, off::Vector{Float64}, wts::Vector{Float64}) (repeats 79984 times)
   @ GLM C:\Users\Win10\.julia\packages\GLM\5CcRd\src\glmfit.jl:63
```

Is this a problem in MLJGLMInterface or GLM?

**Comment by goerch** [comment]
Explicitely converting y to a FPVector solves the problem:

```
using MLJ
using GLM

X, y = @load_boston
yr = GLM.FPVector{Float64}(y)

model = (@load LinearRegressor pkg="GLM")()
_machine = machine(model, X, yr)
fit!(_machine)
y_hat = predict_mean(_machine, X)
_rmse = rmse(yr, y_hat)
println("rmse = ", _rmse)
```

solves the problem

```
[ Info: For silent loading, specify `verbosity=0`.
import MLJGLMInterface ✔
[ Info: Training Machine{LinearRegressor,…} @596.
rmse = 4.725206759835135
```

**Comment by tlienart** [comment]
hmm that's not ideal, I'm also a bit confused since that wasn't required before and we have an explicit compat bound on GLM; anyway if it's required to pass `FPVector` then the thing to do would be to extend `process_inputs` to also take `y` and do the conversion there i.e.: 

https://github.com/JuliaAI/MLJGLMInterface.jl/blob/7468b6d524221b9efc446d5c1ce28c2c872a2357/src/MLJGLMInterface.jl#L77-L81 

would take `y` and return `yr = GLM.FPVector{eltype(y)}(y)` or whatever is required by GLM. 

Before doing that we'd need to make sure that this is required by GLM and, if so, since when.

**Comment by goerch** [comment]
Culprit seems to be

```
function GlmResp(y::AbstractVector{<:Real}, d::D, l::L, off::AbstractVector{<:Real},
                 wts::AbstractVector{<:Real}) where {D, L}
        GlmResp(float(y), d, l, float(off), float(wts))
end
```

My Julia foo is not good enough to assess if this dispatch is generally correct (it is clearly not in our case).

**Comment by tlienart** [comment]
It seems to be a combination of a clash between the `offset` support that was added by @olivierlabayle in the latest release here and this `GlmResp` that loops to infinity. 

We can either rewind the `offset` support (i.e. wind back the latest release here) or figure out why it fails but I don't follow GLM development and don't know their internals.

**Comment by olivierlabayle** [comment]
Hello,

I have checked-out: [0.1.5](https://github.com/JuliaAI/MLJGLMInterface.jl/releases/tag/v0.1.5) and I can reproduce the bug from that release so it's unrelated with the offset.

It turns out this has nothing to do with the `FPVector` type, a simple `Vector` will do fine. If you look at the type of `y` you will see this is a view from a matrix which I guess is not correctly supported. The call `float(y)` will remain a view and not enter the main function. I guess the workaround is to add a `convert(Vector, y)` to the `prepare_inputs` function.

For instance, the following works for me. Note that the end of the code (RMSE) will not work either as the LinearRegressor is a probabilistic model.

```julia

using MLJ

X, y = @load_boston
y = convert(Vector, y)

model = (@load LinearRegressor pkg="GLM")()
_machine = machine(model, X, y)
y = convert(Vector, y)
fit!(_machine)
y_hat = predict(_machine, X)
```

I can probably do that tomorrow. In any case rewinding will not solve the problem.

**Comment by tlienart** [comment]
Thanks for checking this @olivierlabayle :+1:, extending `prepare_inputs` is the easy path forward then. I guess we can just do

```
function prepare_inputs(model, X, y)
    Xminoffset, offset = split_X_offset(X, model.offsetcol)
    Xmatrix   = augment_X(MMI.matrix(Xminoffset), model.fit_intercept)
    return Xmatrix, offset, convert(Vector, y)
end
```

and recuperate that `y` in the various `fit` calls.

**Comment by ablaom** [comment]
> PPS: @ablaom is this recent that @load_* returns a subarray instead of a Vector? 

I dunno but a subarray is an abstract vector and should work fine, and appears indeed to work fine:

```julia
julia> X, y = @load_boston;

julia> yhat = shuffle(y);

julia> rms(yhat, y)
12.515110234821085
```

I think @olivierlabayle 's side remark is that you cannot apply a deterministic measure to what is a probabilistic prediction. You need to use `predict_mean` here instead of `predict` if you want to apply `rmse`.

**Comment by goerch** [comment]
The defect happens in 

```
fit!(_machine)
```

already. Sorry for the confusion.

**Comment by olivierlabayle** [comment]
I've been starting to work on a solution [here](https://github.com/JuliaAI/MLJGLMInterface.jl/pull/10) which seems ok. Unfortunately, as outlined by @goerch I can't really appreciate why the dispatch does what it does, some help would be most welcome. More details are in the pull request comment.

**Comment by OkonSamuel** [comment]
@tlienart , @ablaom, @olivierlabayle  I think this issue has been resolved as I don't experience any such error on my PC.
```julia
julia> using MLJ;

julia> X, y = @load_boston;

julia> model = (@load LinearRegressor pkg="GLM")()
[ Info: For silent loading, specify `verbosity=0`.
import MLJGLMInterface ✔
LinearRegressor(
    fit_intercept = true,
    allowrankdeficient = false,
    offsetcol = nothing)

julia> _machine = machine(model, X, y)
Machine{LinearRegressor,…} trained 0 times; caches data
  model: MLJGLMInterface.LinearRegressor
  args:
    1:  Source @092 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @928 ⏎ `AbstractVector{Continuous}`


julia> fit!(_machine)
[ Info: Training Machine{LinearRegressor,…}.
Machine{LinearRegressor,…} trained 1 time; caches data
  model: MLJGLMInterface.LinearRegressor
  args:
    1:  Source @092 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @928 ⏎ `AbstractVector{Continuous}`


julia> y_hat = predict(_machine, X);

```
```
julia v1.7.1
```
