### ISSUE TITLE
Why is LinearRegressor Probabilistic?

### ISSUE THREAD

**Issue by goerch** [JuliaAI/MLJGLMInterface.jl#9]
```
@with_kw_noshow mutable struct LinearRegressor <: MMI.Probabilistic
    fit_intercept::Bool                 = true
    allowrankdeficient::Bool            = false
    offsetcol::Union{Symbol, Nothing}   = nothing
end
```

It is Deterministic in MLJLinearModels.jl as far as I understand. I also get difficulties to evaluate! rmse even with check_measure=false specified.

**Comment by ablaom** [comment]
Thanks for reporting. This is a common gotcha which https://github.com/JuliaAI/MLJBase.jl/pull/599 (continued by https://github.com/JuliaAI/MLJBase.jl/pull/600) will mitigate. 

The model is probabilistic because `predict` predicts probability distributions, not point values. To get point values, one uses `predict_mean`. 

Your issue is that `prediction_type(LinearRegressor) == :probabilistic` but `prediction_type(rmse) == :deterministic` To evaluate such a model you can:

(i) specify `operation=predict_mean` in `evaluate!` to ensure all measures receive output of `predict_mean` instead of `predict` (which means, currently, all measures must be deterministic). 

(ii) put your model into a pipeline with `mean` at the end. Something like `pipe = @pipeline LinearRegressor y->mean.(y)`. See the [pipeline docs](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Linear-Pipelines) for more. 

In the case of binary probabilistic *classifiers* you have a third option, which is to wrap your model using the built-in `BinaryThresholdPredictor`. 

Hope this helps.

**Comment by tlienart** [comment]
Just to add to the comment above, in GLM there is an explicit assumption of a Gaussian model for the errors, and therefore the prediction is a Gaussian model.

In MLJLM there is no such assumption; still the mean predicted with GLM will match it of course.

In short both solve the same equation ultimately but one makes more assumptions than the other and propagates that in the prediction.
